apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: python-app
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: python-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: python-app
    spec:
      containers:
        - args:
            - sh
            - -c
            - python create_data.py && python remove_outlier.py && python process_data.py
          env:
            - name: DB_HOST
              value: db
            - name: DB_NAME
              value: mydatabase
            - name: DB_PASSWORD
              value: password
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: user
          image: python-app:latest
          name: python-app
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: python-app-claim0
          workingDir: /app
      restartPolicy: Always
      volumes:
        - name: python-app-claim0
          persistentVolumeClaim:
            claimName: python-app-claim0
status: {}
