version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  python-app:
    build: .
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_NAME: mydatabase
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "python create_data.py && python remove_outliers.py && python process_data.py"
    depends_on:
      - db
volumes:
  db_data: